apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "minio.name" . }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: minio-api
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: minio-console
