apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../base
  - namespace.yaml
  - deployment-patch.yaml
  - ingress.yaml

commonLabels:
  environment: prod

