apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      protocol: TCP
      targetPort: amqp
    {{- if .Values.service.managementEnabled }}
    - name: management
      port: {{ .Values.service.managementPort }}
      protocol: TCP
      targetPort: management
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}

