apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ include "vault.namespace" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vault.service.type }}
  ports:
    - port: {{ .Values.vault.service.port }}
      targetPort: 8200
      protocol: TCP
      name: http
    - port: 8201
      targetPort: 8201
      protocol: TCP
      name: cluster
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}

