apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ include "vault.namespace" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault.fullname" . }}-auth
  namespace: {{ include "vault.namespace" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    component: auth
automountServiceAccountToken: true

