apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: go-service-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: go-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: js-gateway-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: js-gateway

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-service-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: python-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: react-frontend-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: react-frontend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csharp-risk-service-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: csharp-risk-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dotnet-service-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dotnet-service

